CREATE TABLE IF NOT EXISTS "Users" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserName" TEXT NOT NULL,
  "FullName" TEXT,
  "EmailID" TEXT
);

CREATE TABLE IF NOT EXISTS "SchemeMaster" (
  "SchemeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SchemeName" TEXT,
  "CreatedBy" INTEGER,
  "CreatedDate" TEXT
);

CREATE TABLE IF NOT EXISTS "PlanMaster" (
  "PlanID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlanName" TEXT,
  "PlanAmount" NUMERIC,
  "SchemeID" INTEGER,
  FOREIGN KEY ("SchemeID") REFERENCES "SchemeMaster"("SchemeID")
);

CREATE TABLE IF NOT EXISTS "MemberRegistration" (
  "MemID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MemberNo" TEXT,
  "MemberFName" TEXT,
  "MemberLName" TEXT,
  "DOB" TEXT,
  "ContactNo" TEXT,
  "EmailID" TEXT,
  "Gender" TEXT,
  "PlanTypeID" INTEGER,
  "WorkoutTypeID" INTEGER,
  "JoiningDate" TEXT,
  "Address" TEXT
);

CREATE TABLE IF NOT EXISTS "PaymentDetails" (
  "PaymentID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MemberID" INTEGER,
  "PlanID" INTEGER,
  "PaymentAmount" NUMERIC,
  "PaymentFromDate" TEXT,
  "PaymentToDate" TEXT,
  "NextRenewalDate" TEXT,
  FOREIGN KEY ("MemberID") REFERENCES "MemberRegistration"("MemID")
);
